name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build_and_package:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip the build directory
        run: 7z a "MistEra-${{ github.ref_name }}.7z" ${{ vars.BUILD_DIR }} -p"era"

      - name: Create GitHub Release and upload artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: MistEra ${{ github.ref_name }}
          files: MistEra-${{ github.ref_name }}.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
